### PR TITLE
new institutions for Guesh's handlist

### PR DESCRIPTION
**Pull request by eu-genia**

### CODE REVIEW

**Review by DenisNosnitsin1970 — CHANGES_REQUESTED** [review]
In all three cases, qushet indication is missing (in many cases the name of the institution contains the qushet names). Please check this.

**Comment by eu-genia** [comment]
Dear Guesh, you may not merge Pull Requests when there are open questions. You must wait for the review, then the entries should be edited, and only when all have approved the PR must be merged.
Now I will open a new PR in order to edit the qushat, if you provide me with the necessary information. Thank you.

**Comment by GueshSol** [comment]
@eu-genia and @DenisNosnitsin1970,
I am very sorry for the technical error in merging the review; it was just a fatal mistake. As to the information concerning local administration information, I wrote to @eu-genia last time clearly. Find here gain, but it seems there is confusion in the number of the monasteries. I visited three;
1. GT- Guya Takla Ḥaymānot ጉያ ተክለ ሐይማኖት (this rock-hewn Church is also called Takla Ḥaymānot Tāmba  ተክለ ሐይማኖትታምባ and Māryām  Tāmbā. ማርያም ታምባ)
 There are two tabots one for Takla Ḥaymānot and the other for Saint Mary. 
Location 
Region Tigray
District Tamben
Worada Qolla Tamben
Tabya: (Ṭabyā): Guya
Kueshet: Guya
coordinates 13.6205728 38.8256511
2. AS- Ambirsǝwā Mikaʾel (አምቢርስዋ ሚካኤል)  tabot (1), Saint Michael (ቅዱስ ሚካኢል)
Location
Region: Tigray
District: Tamben
Worada: Qolla Tamben
Tabya Simrat: (Ṭabyā): Sǝmrat
Kushet:Ambirsǝwā 
Coordinates: 13.632607 38.855276
3. JM- Ǧǝwāmāra Mikaʾel  (ጅዋማረ ሚካኤል) tabots (3); Saint Michael (ቅዱስ ሚካኢል) ,ʾAbuna Tanśǝʾa Wald (አቡነ ተንስአ ወልድ), and Abuna Maʿāzā Dǝngǝl (አቡነ
መዓዛ ድንግል)
Location
Region: Tigray
District: Tamben
Worada: Qollā Tamben
Tabya (Ṭabyā): Ǧǝwāmāra
Kushet:Ǧǝwāmāra
coordinates:  13.650557 38.670969
The problem with the third monastery was I had a chance to digitize only a single manuscript (no chance to take additional pictures as there was a problem with the priests). I did not mention I counted 200 manuscripts in Ǧǝwāmāra Mikaʾel. I only said 198 from Guya Takla Ḥaymānot and 200 from Ambirsǝwā Mikaʾel. Thus, three institutions are required with their own geographical information.
Many thanks!

**Comment by eu-genia** [comment]
Dear Guesh,
thank you, I will create a new PR with added qushat.
Note that there is nothing wrong in being asked to supply missing information.
But there is really **no need to be dishonest** and claim that you had provided it already and had written to me "last time clearly".
See the email below, there was no information on qushat, or I would have used it.
Honesty and clarity are always an advantage, and adding or forgetting is really nothing bad. 

image

**Comment by eu-genia** [comment]
And where is the confusion with the number of the monasteries? Please do check the files in this pull request. There are three new files containing the information from the email and from the written report, no available at https://doi.org/10.25592/uhhfdm.13989 
If there is anything confused or missing please review the files and provide feedback. Thank you.

**Comment by GueshSol** [comment]
@eu-genia 
I am very sorry if you understand it that way. I want to say monasteries Ambirswa and Juwamara are written in the same branch and my intention is to indicate that I wrote you three institutions last time. My reply is not a direct quotation. I added Kushet in three of them and even Changed Kable into Tabya obviously. You mistakenly wrote as I counted 200 manuscripts in Juwamara Mikael; again I say I did not. There is nothing that I can be considered as dishonest. if you want to check everything I can give you their contact details (for the churches) and you can check everything. 
Many thanks for your understanding.

**Comment by GueshSol** [comment]
@eu-genia 
Institution request
Maybe if you are able to see the screenshot in this link. it might be clear what I mean.

**Comment by eu-genia** [comment]
This is exactly why I ask for peer review when doing the Pull Request. You should mark these corrections in the XML file when you receive the GitHub notification, then the files are fixed. Only when everything is correct and everyone has approved can a record be merged.

**Pull request merged**
