### PR TITLE
Create INS1011AratoMaryamMagdalawit.xml

### PR DESCRIPTION
**Pull request by DenisNosnitsin1970**
The church mentioned in Abb 72.

### CODE REVIEW

**Comment by CarstenHoffmannMarburg** [comment]
It would be nice to find a reference to the exact location of Arato - preferably in LOC7441Arato if it is clear. My guess is that it should be Arato, east of Mekele.

**Review by CarstenHoffmannMarburg — APPROVED** [review]

**Comment by DenisNosnitsin1970** [comment]
I know, there is a place called 'Arato in Tigray, but the connection between both seems to me very hypothetical. I will try to check.

**Comment by thea-m** [comment]
(I think it would be good in the future to compose less lengthy IDs, maybe just the abbreviation (as according to guidelines) that will be used in the manuscript IDs of the repository. Very long IDs can be a bit cumbersome)

**Comment by eu-genia** [comment]
> (I think it would be good in the future to compose less lengthy IDs, maybe just the abbreviation (as according to guidelines) that will be used in the manuscript IDs of the repository. Very long IDs can be a bit cumbersome)

not only cumbersome, but from a certain length it may be impossible to parse for the code.

**Review by eu-genia — APPROVED** [review]

**Pull request merged**
