### PR TITLE
Updates to Central Tigray Inst with qushat

### PR DESCRIPTION
**Pull request by eu-genia**
for https://github.com/BetaMasaheft/Documentation/milestone/45
follow up to https://github.com/BetaMasaheft/Institutions/pull/85

### CODE REVIEW

**Comment by eu-genia** [comment]
Guesh - when you are pinned for review, you are supposed to
(1) go to the files tab
(2) check and if there is anything to correct you click on the "+" sign on the left of the line with the error and type what you think must be changed
(3) go to "Review" button on top and select if you approve or request changes or just comment

DO NOT MERGE

image

**Review by GueshSol — APPROVED** [review]
@eu-genia,
I found it good.

**Comment by eu-genia** [comment]
See also https://www.betamasaheft.uni-hamburg.de/manuscripts/newresearch/centraltigray.html

**Review by DenisNosnitsin1970 — APPROVED** [review]

**Comment by GueshSol** [comment]
Dear @Eugenia Sokolinski ***@***.***>,
Thank you very much for the improvement and for publishing my field trip
report online on the website of the Bm project.

**Pull request merged**
