### PR TITLE
Institution renamed

### PR DESCRIPTION
**Pull request by vitagrazia81**
I have renamed Leipzig as 0974, as you suggested. Is it now fine? Thank you.

### CODE REVIEW

**Review by eu-genia — APPROVED** [review]
yes, thank you, make sure you also correct the MSS records that point to UBL

**Review by thea-m — CHANGES_REQUESTED** [review]
Thank you, Vita! The ID change is correct. Two small things remain: 1. please rename the file, as the file's name and ID must be identical (like you would rename any file, right mouse click on the file name in atom or explorer and "rename") and 2. Please check that the old ID has been used in no other records. If it has been used, please substitute it there by the new ID and make a PR for this change as well. Let me know if anything is unclear!

**Comment by thea-m** [comment]
(I see now that the renaming already went through, thanks!)

**Comment by vitagrazia81** [comment]
Thank you Dorothea. It means that is all fine now?! Yes, I have renamed both already.

**Comment by thea-m** [comment]
Yes, with the institution record everything is fine. Then I await the PR for the change of the reference in the other records :)

**Comment by vitagrazia81** [comment]
Good. thanks Dorothea.

**Pull request merged**
